name: Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: |
          git diff-tree --no-commit-id --name-only -r HEAD~1 HEAD  > changed_files.txt
          cat changed_files.txt

      - run: |
          grep -E 'schema.prisma|pnpm-lock.yaml|deploy.yml' changed_files.txt > filtered_files.txt || true
          cat filtered_files.txt

      - id: check_changes
        run: |
          cat filtered_files.txt
          if [[ -s "filtered_files.txt" ]]; then
            echo "::set-output name=changes_exist::true"
          else
            echo "::set-output name=changes_exist::false"
          fi

      - id: my_vars
        run: |
          echo "::set-output name=tar_name::$(date +'%Y%m%dT%H%M%S')-$(echo $GITHUB_SHA | cut -c 1-7)"

      - run: |
          tar --exclude .git --exclude .github --exclude "libquery_engine-*.so.node" -czf ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz .

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.my_vars.outputs.tar_name }}
          path: ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz

      - run: |
          echo "${{ secrets.SERVER_KEY }}" > ${{ runner.temp }}/private_key.pem
          chmod 600 ${{ runner.temp }}/private_key.pem
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keygen -y -f ${{ runner.temp }}/private_key.pem > ${{ runner.temp }}/private_key.pub
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - run: |
          scp -i ${{ runner.temp }}/private_key.pem ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/chat/v1-sdk-api

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /root/chat/v1-sdk-api
            mkdir ${{ steps.my_vars.outputs.tar_name }}
            tar -xzvf ${{ steps.my_vars.outputs.tar_name }}.tar.gz -C ./${{ steps.my_vars.outputs.tar_name }}

      - if: steps.check_changes.outputs.changes_exist == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /root/chat/v1-sdk-api
            cp ${{ steps.my_vars.outputs.tar_name }}/package.json release/package.json
            cp ${{ steps.my_vars.outputs.tar_name }}/pnpm-lock.yml release/pnpm-lock.yml
            cd release
            pnpm install --registry=https://registry.npmmirror.com
            cd ..
            cp -r ${{ steps.my_vars.outputs.tar_name }}/node_modules release/node_modules
            touch release/${{ steps.my_vars.outputs.tar_name }}-pnpm-install.txt

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /root/chat/v1-sdk-api
            cp ${{ steps.my_vars.outputs.tar_name }} release
            touch release/${{ steps.my_vars.outputs.tar_name }}.txt
            pm2 restart v1-sdk-api
